spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_declare?characterEncoding=UTF-8
    username: root
    password: 123456
    tomcat-jdbc: com.alibaba.datasource.pool.DruidDataSource
    initialSize: 20                                #初始化连接大小
    minIdle: 5                                     #最小连接池数量
    maxActive: 20                                  #最大连接池数量
    maxWait: 60000                                 #获取连接时最大等待时间，单位毫秒
    timeBetweenEvictionRunsMillis: 60000           #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000             #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM tb_role         #测试连接
    testWhileIdle: true                            #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
    testOnBorrow: false                            #获取连接时执行检测，建议关闭，影响性能
    testOnReturn: false                            #归还连接时执行检测，建议关闭，影响性能
    poolPreparedStatements: false                  #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
    maxPoolPreparedStatementPerConnectionSize: 20  #开启poolPreparedStatements后生效
    filters: stat,wall,log4j         # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
                                                   #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true                   # 合并多个DruidDataSource的监控数据
  jpa:
    show-sql: true    #开发时打开sql显示
  thymeleaf:
    cache: false      #开发时关闭缓存以查看实时页面
    mode: LEGACYHTML5 #非完全严格检查,严格使用HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html


